name: Gradle Build and Test

# on means that this is a trigger waiting for something to happen.
on:

  push: 
    branches: [ development ]
  # pull_request means that this is a trigger waiting for a pull request to be made.
  pull_request:
    # This event will only trigger if the pull request is made to the development branch.
    branches: [ development ]

# jobs is a list of jobs that will be run.    
jobs:
  # on build job these are the steps that will be run. 
  build:

    # This is the operating system that the job will run on.
    runs-on: ${{ matrix.os }}
    # This allows us to use multiple variables. 
    strategy:
      # This is the matrix of variables that will be used.
      matrix:
        # This is the list of operating systems that will be used.
        os: [ubuntu-latest, windows-latest, macos-latest]

    # In order for the job to be run it needs to check out the code.
    steps:
    - uses: actions/checkout@v2

    # This is the Java Development Kit version that will be used. I used this one because this seems to be the version that most teammates are using.
    - name: Set up JDK 17
      # Sets up the a Java environment for use in actions.
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        # This pulls the jdk from the adoptopenjdk website which provides open source OpenJDK binaries.
        distribution: 'adopt'

    # This will allow GitHub actions to use and execute gradle and the gradle wrapper.
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Standard gradle build command.  
    - name: Build with Gradle
      run: ./gradlew build

    # Standard gradle test command.
    - name: Test with Gradle
      run: ./gradlew test

    # This is will generate a code coverage report.  
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1  
